---
version: '3.8'
services:
  async_ruby:
    image: meleneth/asyncbenchmarks_ruby
    build:
      context: "./async_ruby"
    ports:
    - 8100:8000

  nginx:
    image: meleneth/asyncbenchmarks_nginx
    build:
      context: "./nginx"
    ports:
    - 8110:80

  c_notrix:
    image: meleneth/asyncbenchmarks_c_multithreaded
    build:
      context: "./c_multithreaded"
    ports:
    - 8120:8000

  rusted_rocket:
    image: meleneth/asyncbenchmarks_rusted_rocket
    build:
      context: "./rusted_rocket"
    ports:
    - 8130:8130
